# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowMenu.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import client

QDialogStyle = "background-color:#333333;color:#333333;max-width:480px;min-width:480px;max-height:320px;min-height:320px;"
QButtonStyle = "QPushButton{border-radius:5px;background-color: #f0f0f0;border-width: 1px;border-color: #333333;min-width:  96px;max-width:  96px;min-height: 24px;max-height: 24px}QPushButton:hover{background-color: #dedede;color: #f0f0f0;border-color: #f0f0f0;}"
QListWidgetStyle = "QListWidget{border-radius:2px;background-color:#f0f0f0;color:#333333;max-width:280px;min-width:280px;max-height:180px;min-height:180px;}QListWidget::item:selected{border-radius:1px;background:#444444;color: #f0f0f0;}"

class windowMenu(object):
    def setupUi(self, windowMenu):
        windowMenu.setObjectName("windowMenu")
        windowMenu.resize(480, 320)
        windowMenu.setMinimumSize(QtCore.QSize(480, 320))
        windowMenu.setMaximumSize(QtCore.QSize(480, 320))
        windowMenu.setStyleSheet(QDialogStyle)
        self.verticalLayoutWidget = QtWidgets.QWidget(windowMenu)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 481, 321))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.enterListener = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.enterListener.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.enterListener.setObjectName("enterListener")
        self.enterListener.setStyleSheet(QButtonStyle)
        self.horizontalLayout_4.addWidget(self.enterListener)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.enterClicker = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.enterClicker.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.enterClicker.setObjectName("enterClicker")
        self.enterClicker.setStyleSheet(QButtonStyle)
        self.horizontalLayout_4.addWidget(self.enterClicker)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(20, 24, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem7)

        self.retranslateUi(windowMenu)
        QtCore.QMetaObject.connectSlotsByName(windowMenu)

    def retranslateUi(self, windowMenu):
        _translate = QtCore.QCoreApplication.translate
        windowMenu.setWindowTitle(_translate("windowMenu", "windowMenu"))
        self.enterListener.setText(_translate("windowMenu", "Listener"))
        self.enterClicker.setText(_translate("windowMenu", "Clicker"))

class windowListener(object):
    def setupUi(self, windowListener):
        windowListener.setObjectName("windowListener")
        windowListener.resize(480, 320)
        windowListener.setMinimumSize(QtCore.QSize(480, 320))
        windowListener.setMaximumSize(QtCore.QSize(480, 320))
        windowListener.setStyleSheet(QDialogStyle)
        self.verticalLayoutWidget = QtWidgets.QWidget(windowListener)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 481, 321))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.startListener = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.startListener.setMinimumSize(QtCore.QSize(0, 24))
        self.startListener.setMaximumSize(QtCore.QSize(16777215, 24))
        self.startListener.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.startListener.setObjectName("startListener")
        self.startListener.setStyleSheet(QButtonStyle)
        self.horizontalLayout_4.addWidget(self.startListener)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.stopListener = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.stopListener.setMinimumSize(QtCore.QSize(0, 24))
        self.stopListener.setMaximumSize(QtCore.QSize(16777215, 24))
        self.stopListener.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.stopListener.setObjectName("stopListener")
        self.stopListener.setStyleSheet(QButtonStyle)
        self.horizontalLayout_4.addWidget(self.stopListener)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem6 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.returnListener = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.returnListener.setMinimumSize(QtCore.QSize(0, 24))
        self.returnListener.setMaximumSize(QtCore.QSize(16777215, 24))
        self.returnListener.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.returnListener.setObjectName("returnListener")
        self.returnListener.setStyleSheet(QButtonStyle)
        self.horizontalLayout_5.addWidget(self.returnListener)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(windowListener)
        QtCore.QMetaObject.connectSlotsByName(windowListener)

    def retranslateUi(self, windowListener):
        _translate = QtCore.QCoreApplication.translate
        windowListener.setWindowTitle(_translate("windowListener", "windowListener"))
        self.startListener.setText(_translate("windowListener", "Start Listener"))
        self.stopListener.setText(_translate("windowListener", "Stop Listener"))
        self.returnListener.setText(_translate("windowListener", "Return"))

class windowClicker(object):
    def setupUi(self, windowClicker):
        windowClicker.setObjectName("windowClicker")
        windowClicker.setWindowModality(QtCore.Qt.NonModal)
        windowClicker.resize(480, 320)
        windowClicker.setMinimumSize(QtCore.QSize(480, 320))
        windowClicker.setMaximumSize(QtCore.QSize(480, 320))
        windowClicker.setStyleSheet(QDialogStyle)
        self.verticalLayoutWidget = QtWidgets.QWidget(windowClicker)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, -1, 490, 321))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 24, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(96, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.collectionsList = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.collectionsList.setMinimumSize(QtCore.QSize(268, 144))
        self.collectionsList.setMaximumSize(QtCore.QSize(268, 144))
        self.collectionsList.setObjectName("collectionsList")
        self.collectionsList.setStyleSheet(QListWidgetStyle)
        self.horizontalLayout_4.addWidget(self.collectionsList)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.refreshList = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.refreshList.setMinimumSize(QtCore.QSize(96, 24))
        self.refreshList.setMaximumSize(QtCore.QSize(96, 24))
        self.refreshList.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.refreshList.setObjectName("refreshList")
        self.refreshList.setStyleSheet(QButtonStyle)
        self.verticalLayout_4.addWidget(self.refreshList)
        self.dropRecord = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.dropRecord.setMinimumSize(QtCore.QSize(96, 24))
        self.dropRecord.setMaximumSize(QtCore.QSize(96, 24))
        self.dropRecord.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.dropRecord.setObjectName("dropRecord")
        self.dropRecord.setStyleSheet(QButtonStyle)
        self.verticalLayout_4.addWidget(self.dropRecord)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.startClicker = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.startClicker.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.startClicker.setObjectName("startClicker")
        self.startClicker.setStyleSheet(QButtonStyle)
        self.horizontalLayout.addWidget(self.startClicker)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.stopClicker = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.stopClicker.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.stopClicker.setObjectName("stopClicker")
        self.stopClicker.setStyleSheet(QButtonStyle)
        self.horizontalLayout.addWidget(self.stopClicker)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.returnClicker = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.returnClicker.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.returnClicker.setObjectName("returnClicker")
        self.returnClicker.setStyleSheet(QButtonStyle)
        self.horizontalLayout_5.addWidget(self.returnClicker)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(windowClicker)
        QtCore.QMetaObject.connectSlotsByName(windowClicker)

    def retranslateUi(self, windowClicker):
        _translate = QtCore.QCoreApplication.translate
        windowClicker.setWindowTitle(_translate("windowClicker", "Dialog"))
        self.refreshList.setText(_translate("windowClicker", "Refresh List"))
        self.dropRecord.setText(_translate("windowClicker", "Delete Record"))
        self.startClicker.setText(_translate("windowClicker", "Start Clicker"))
        self.stopClicker.setText(_translate("windowClicker", "Stop Clicker"))
        self.returnClicker.setText(_translate("windowClicker", "Return"))
        self.collectionsList.addItems(client.database.update_collections())
        __sortingEnabled = self.collectionsList.isSortingEnabled()
        self.collectionsList.setSortingEnabled(__sortingEnabled)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    windowMenu = QtWidgets.QwindowMenu()
    ui = windowMenu()
    ui.setupUi(windowMenu)
    windowMenu.show()
    sys.exit(app.exec_())

