# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowMenu.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets
import client

QDialogStyle = "background-color:#333333;color:#333333;max-width:480px;min-width:480px;max-height:320px;min-height:320px;"
QButtonStyle = "QPushButton{border-radius:5px;background-color: #f0f0f0;border-width: 1px;border-color: #333333;min-width:  96px;max-width:  96px;min-height: 24px;max-height: 24px}QPushButton:hover{background-color: #dedede;border-color: #f0f0f0;}"
QLabelStyle = "QLabel{min-height: 24px;max-height: 24px;color: #f0f0f0;}"
QListWidgetStyle = "QListWidget{border-radius:2px;background-color:#f0f0f0;color:#333333;max-width:268px;min-width:268px;max-height:127px;min-height:127px;}QListWidget::item:selected{border-radius:1px;background:#444444;color: #f0f0f0;}"

class windowMenu(object):
    def setupUi(self, windowMenu):
        windowMenu.setObjectName("windowMenu")
        windowMenu.resize(480, 320)
        windowMenu.setMinimumSize(QtCore.QSize(480, 320))
        windowMenu.setMaximumSize(QtCore.QSize(480, 320))
        windowMenu.setStyleSheet(QDialogStyle)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(windowMenu)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(-1, -1, 481, 321))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setContentsMargins(-1, -1, 0, 0)
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem)
        self.labelWelcome = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.labelWelcome.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.labelWelcome.setAlignment(QtCore.Qt.AlignCenter)
        self.labelWelcome.setObjectName("labelWelcome")
        self.labelWelcome.setStyleSheet(QLabelStyle)
        self.verticalLayout_10.addWidget(self.labelWelcome)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.verticalLayout_10)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(20, 24, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.enterListener = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.enterListener.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.enterListener.setObjectName("enterListener")
        self.enterListener.setStyleSheet(QButtonStyle)
        self.horizontalLayout_8.addWidget(self.enterListener)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.enterClicker = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.enterClicker.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.enterClicker.setObjectName("enterClicker")
        self.enterClicker.setStyleSheet(QButtonStyle)
        self.horizontalLayout_8.addWidget(self.enterClicker)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem8)
        spacerItem9 = QtWidgets.QSpacerItem(20, 24, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem9)
        self.verticalLayout_2.addLayout(self.verticalLayout_7)

        self.retranslateUi(windowMenu)
        QtCore.QMetaObject.connectSlotsByName(windowMenu)

    def retranslateUi(self, windowMenu):
        _translate = QtCore.QCoreApplication.translate
        windowMenu.setWindowTitle(_translate("windowMenu", "GUIhelper"))
        self.labelWelcome.setText(_translate("windowMenu", "Welcome to GUIhelper. Use the buttons to navigate the app."))
        self.enterListener.setText(_translate("windowMenu", "Listener"))
        self.enterClicker.setText(_translate("windowMenu", "Clicker"))

class windowListener(object):
    def setupUi(self, windowListener):
        windowListener.setObjectName("windowListener")
        windowListener.resize(480, 320)
        windowListener.setMinimumSize(QtCore.QSize(480, 320))
        windowListener.setMaximumSize(QtCore.QSize(480, 320))
        windowListener.setStyleSheet(QDialogStyle)
        self.verticalLayoutWidget = QtWidgets.QWidget(windowListener)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 481, 321))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setContentsMargins(-1, -1, 0, 0)
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem)
        self.labelListener = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelListener.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.labelListener.setAlignment(QtCore.Qt.AlignCenter)
        self.labelListener.setObjectName("labelListener")
        self.labelListener.setStyleSheet(QLabelStyle)
        self.verticalLayout_10.addWidget(self.labelListener)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.verticalLayout_10)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(20, 24, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.startListener = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.startListener.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.startListener.setObjectName("startListener")
        self.startListener.setStyleSheet(QButtonStyle)
        self.horizontalLayout_8.addWidget(self.startListener)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.stopListener = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.stopListener.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.stopListener.setObjectName("stopListener")
        self.stopListener.setStyleSheet(QButtonStyle)
        self.horizontalLayout_8.addWidget(self.stopListener)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        spacerItem8 = QtWidgets.QSpacerItem(20, 34, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem9)
        self.returnListener = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.returnListener.setMinimumSize(QtCore.QSize(0, 24))
        self.returnListener.setMaximumSize(QtCore.QSize(16777215, 24))
        self.returnListener.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.returnListener.setObjectName("returnListener")
        self.returnListener.setStyleSheet(QButtonStyle)
        self.horizontalLayout_9.addWidget(self.returnListener)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem10)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.verticalLayout_2.addLayout(self.verticalLayout_7)

        self.retranslateUi(windowListener)
        QtCore.QMetaObject.connectSlotsByName(windowListener)

    def retranslateUi(self, windowListener):
        _translate = QtCore.QCoreApplication.translate
        windowListener.setWindowTitle(_translate("windowListener", "Listener"))
        self.labelListener.setText(_translate("windowListener", "Press L.Alt+Esc+Z to stop recording."))
        self.startListener.setText(_translate("windowListener", "Start Listener"))
        self.stopListener.setText(_translate("windowListener", "Stop Listener"))
        self.returnListener.setText(_translate("windowListener", "Return"))

class windowClicker(object):
    def setupUi(self, windowClicker):
        windowClicker.setObjectName("windowClicker")
        windowClicker.setWindowModality(QtCore.Qt.NonModal)
        windowClicker.resize(480, 320)
        windowClicker.setMinimumSize(QtCore.QSize(480, 320))
        windowClicker.setMaximumSize(QtCore.QSize(480, 320))
        windowClicker.setStyleSheet(QDialogStyle)
        self.verticalLayoutWidget = QtWidgets.QWidget(windowClicker)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 490, 322))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(96, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.collectionsList = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.collectionsList.setMinimumSize(QtCore.QSize(268, 120))
        self.collectionsList.setMaximumSize(QtCore.QSize(268, 120))
        self.collectionsList.setObjectName("collectionsList")
        self.collectionsList.setStyleSheet(QListWidgetStyle)
        self.horizontalLayout_4.addWidget(self.collectionsList)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.refreshList = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.refreshList.setMinimumSize(QtCore.QSize(96, 24))
        self.refreshList.setMaximumSize(QtCore.QSize(96, 24))
        self.refreshList.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.refreshList.setObjectName("refreshList")
        self.refreshList.setStyleSheet(QButtonStyle)
        self.verticalLayout_4.addWidget(self.refreshList)
        self.dropRecord = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.dropRecord.setMinimumSize(QtCore.QSize(96, 24))
        self.dropRecord.setMaximumSize(QtCore.QSize(96, 24))
        self.dropRecord.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.dropRecord.setObjectName("dropRecord")
        self.dropRecord.setStyleSheet(QButtonStyle)
        self.verticalLayout_4.addWidget(self.dropRecord)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelClicker = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelClicker.setMinimumSize(QtCore.QSize(96, 24))
        self.labelClicker.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.labelClicker.setAlignment(QtCore.Qt.AlignCenter)
        self.labelClicker.setObjectName("labelClicker")
        self.labelClicker.setStyleSheet(QLabelStyle)
        self.verticalLayout_2.addWidget(self.labelClicker)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.startClicker = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.startClicker.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.startClicker.setObjectName("startClicker")
        self.startClicker.setStyleSheet(QButtonStyle)
        self.horizontalLayout.addWidget(self.startClicker)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.stopClicker = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.stopClicker.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.stopClicker.setObjectName("stopClicker")
        self.stopClicker.setStyleSheet(QButtonStyle)
        self.horizontalLayout.addWidget(self.stopClicker)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.returnClicker = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.returnClicker.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.returnClicker.setObjectName("returnClicker")
        self.returnClicker.setStyleSheet(QButtonStyle)
        self.horizontalLayout_5.addWidget(self.returnClicker)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(windowClicker)
        QtCore.QMetaObject.connectSlotsByName(windowClicker)

    def retranslateUi(self, windowClicker):
        _translate = QtCore.QCoreApplication.translate
        windowClicker.setWindowTitle(_translate("windowClicker", "Clicker"))
        self.refreshList.setText(_translate("windowClicker", "Refresh List"))
        self.dropRecord.setText(_translate("windowClicker", "Delete Record"))
        self.labelClicker.setText(_translate("windowClicker", "Pick a record from list that you want to simulate. Press L.Alt+Esc+Z to cancel simulating."))
        self.startClicker.setText(_translate("windowClicker", "Start Clicker"))
        self.stopClicker.setText(_translate("windowClicker", "Stop Clicker"))
        self.returnClicker.setText(_translate("windowClicker", "Return"))
        self.collectionsList.addItems(client.database.update_collections())
        __sortingEnabled = self.collectionsList.isSortingEnabled()
        self.collectionsList.setSortingEnabled(__sortingEnabled)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    windowMenu = QtWidgets.QwindowMenu()
    ui = windowMenu()
    ui.setupUi(windowMenu)
    windowMenu.show()
    sys.exit(app.exec_())

